### ISSUE TITLE
Install problems...

### ISSUE THREAD

**Issue by ktiedt** [Hyra/Frickle#3]
After following the few steps to get this up and running I ran into 3 problems

1) clone was the wrong version
2) detective was not found
3) node-sass bindings reportedly not installed (even after doing an npm link and an npm install -g this cant seem to resolve -- the other 2 problems were easy resolutions)

This on the latest OS X and node 0.10.28

**Comment by savager** [comment]
You can solve the node-sass one by uninstalling it and installing gulp-sass

**Comment by svikasg** [comment]
For node versions 4 & 5,

Do the following for node-sass issues while running npm install

```
npm uninstall --save-dev gulp-sass
npm install --save-dev gulp-sass@3
```

[Source](http://stackoverflow.com/a/32666240)
